##
# Defaults
AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - submodules/**/*
  Include:
    - Rakefile.rb
    - rake/tasks/*.rake
    - nanoc/rules/*.rules
    - nanoc/rules/**/**/*.rules
    - nanoc/lib/*.rb
    - nanoc/lib/**/*.rb
    - nanoc/lib/**/**.rb

##
# Defaults: standard-rb
require:
  - standard
inherit_gem:
  standard: config/base.yml

##
# Enabled
Style/FrozenStringLiteralComment:
  Enabled: true
Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

##
# Disabled
Style/MixinUsage:
  Exclude:
    - Rakefile.rb
Style/SuperArguments:
  Exclude:
    - nanoc/lib/nanoc/extension/anonymous_filter.rb
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/ArgumentAlignment:
  Enabled: false
Layout/ArrayAlignment:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
