name: Prepare environment

runs:
  using: composite
  steps:
  - name: Setup Ruby
    uses: ruby/setup-ruby@v1
    with:
      ruby-version: 3.3
  - name: Setup NodeJS
    uses: actions/setup-node@v2
    with:
      node-version: 16
      cache: npm
  - name: Setup packages
    shell: bash
    run: |
      bin/setup
    
