name: The Quran

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SASS_PATH: ./src/css/

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v2
    - name: Prepare environment
      uses: './.github/actions/prepare-env'
    - name: Add HTMLTidy
      run: sudo apt-get install tidy
    - name: ci
      run: rake ci
