name: The Quran

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SASS_PATH: ./src/css/

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v2
    - name: Prepare environment
      uses: './.github/actions/prepare-env'
    - name: eslint
      run: bundle exec rake lint:eslint
    - name: rubocop
      run: bundle exec rake lint:rubocop
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v2
    - name: Prepare environment
      uses: './.github/actions/prepare-env'
    - name: nanoc
      run: bundle exec rake build
